/**
 * types/index.ts
 * App-level type exports — re-exports the generated Database type and
 * convenience Row types for every Phase 1 table.
 *
 * Import generated types via `types/database.ts` (generated by supabase gen types).
 * Import convenience types via this file.
 */
export type { Database } from "./database";
export type { Json } from "./database";

import type { Database } from "./database";

// ─── Row types ───────────────────────────────────────────────────────────────

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Event = Database["public"]["Tables"]["events"]["Row"];
export type EventLocation =
  Database["public"]["Tables"]["event_locations"]["Row"];
export type ChecklistItem =
  Database["public"]["Tables"]["checklist_items"]["Row"];
export type BudgetCategory =
  Database["public"]["Tables"]["budget_categories"]["Row"];
export type Expense = Database["public"]["Tables"]["expenses"]["Row"];
export type ReceiptFile = Database["public"]["Tables"]["receipt_files"]["Row"];
export type Guest = Database["public"]["Tables"]["guests"]["Row"];
export type RsvpToken = Database["public"]["Tables"]["rsvp_tokens"]["Row"];
export type RsvpResponse =
  Database["public"]["Tables"]["rsvp_responses"]["Row"];
export type EventFile = Database["public"]["Tables"]["event_files"]["Row"];
export type EventInvitation =
  Database["public"]["Tables"]["event_invitations"]["Row"];

// ─── Insert types (useful for Server Actions) ────────────────────────────────

export type ProfileInsert =
  Database["public"]["Tables"]["profiles"]["Insert"];
export type EventInsert = Database["public"]["Tables"]["events"]["Insert"];
export type EventLocationInsert =
  Database["public"]["Tables"]["event_locations"]["Insert"];
export type ChecklistItemInsert =
  Database["public"]["Tables"]["checklist_items"]["Insert"];
export type BudgetCategoryInsert =
  Database["public"]["Tables"]["budget_categories"]["Insert"];
export type ExpenseInsert = Database["public"]["Tables"]["expenses"]["Insert"];
export type GuestInsert = Database["public"]["Tables"]["guests"]["Insert"];
export type RsvpResponseInsert =
  Database["public"]["Tables"]["rsvp_responses"]["Insert"];
export type EventFileInsert =
  Database["public"]["Tables"]["event_files"]["Insert"];
export type EventInvitationInsert =
  Database["public"]["Tables"]["event_invitations"]["Insert"];
